export const MockResult = [
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Edition de logiciels applicatifs',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31000',
        company_name: 'MDP',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 1.201609999999993,
        id: 4636621,
        is_high_potential: true,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'Edition de logiciel',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Conseil en informatique',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31000',
        company_name: 'SCALLIAN',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 5,
        id: 8865324,
        is_high_potential: false,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'Conseil en informatique',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Edition de logiciels applicatifs',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31770',
        company_name: 'Airbus',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 3.201609999999993,
        id: 9165843,
        is_high_potential: true,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'Aéronautique',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Conseil en informatique',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31557',
        company_name: 'CGI',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 1.8201609999999993,
        id: 9977568,
        is_high_potential: false,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'ESN',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Edition de logiciels applicatifs',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31900',
        company_name: 'Capgemini',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 3.8201609999999993,
        id: 4569876,
        is_high_potential: true,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'ESN',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Conseil en informatique',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Balma',
        citycode: '31044',
        company_name: 'GROUPAMA',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 4.4201609999999993,
        id: 8231062,
        is_high_potential: false,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'Assurance',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Edition de logiciels applicatifs',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31000',
        company_name: 'La banque Postale',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 0.4201609999999993,
        id: 1036845,
        is_high_potential: true,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'Banque et assurances',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Conseil en informatique',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31000',
        company_name: 'FRAM',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 3.201609999999993,
        id: 6103856,
        is_high_potential: false,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'Agence de voyage',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Edition de logiciels applicatifs',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31000',
        company_name: 'FNAC',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 2.720160999999993,
        id: 9400056,
        is_high_potential: true,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'Vendeur culturel',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Conseil en informatique',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31000',
        company_name: 'ATOS',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 4.4201609999999993,
        id: 1669485,
        is_high_potential: false,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'ESN militaire',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Edition de logiciels applicatifs',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31000',
        company_name: 'ALTEN',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 1.4201609999999993,
        id: 8455999,
        is_high_potential: true,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'ESN',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
  {
    hits: 0,
    params: {
      citycode: ['31000'],
      department: [''],
      page: 1,
      page_size: 2,
      postcode: ['31000'],
      rome: ['D1102'],
      sort_by: '',
      sort_direction: '',
    },
    resolved_params: {
      jobs: [
        {
          display: 'Conseil en informatique',
          selection: '',
          type: 'rome',
          value: 'D1102',
        },
      ],
      locations: [
        {
          display: 'Toulouse',
          geo: {
            latitude: 49.1196,
            longitude: 6.1764,
          },
          selection: '',
          type: 'city',
          value: '31000',
        },
      ],
    },
    items: [
      {
        city: 'Toulouse',
        citycode: '31000',
        company_name: 'INETUM',
        department: 'Haute-Garonne',
        department_number: 31,
        headcount_max: '5',
        headcount_min: '3',
        hiring_potential: 4.4201609999999993,
        id: 7761002,
        is_high_potential: false,
        location: {
          lat: 49.1196,
          lon: 6.17373,
        },
        naf: '4781Z',
        naf_label: 'ESN',
        office_name: '',
        postcode: '31000',
        region: 'Occitanie',
        rome: 'D1102',
        siret: '30509416100034',
      },
    ],
  },
];
